# Generated by Django 2.2.3 on 2019-07-10 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weekly_report', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='bp_reason',
        ),
        migrations.RemoveField(
            model_name='report',
            name='bp_title',
        ),
        migrations.RemoveField(
            model_name='report',
            name='consultation',
        ),
        migrations.RemoveField(
            model_name='report',
            name='deadline2',
        ),
        migrations.RemoveField(
            model_name='report',
            name='deadline3',
        ),
        migrations.RemoveField(
            model_name='report',
            name='effort',
        ),
        migrations.RemoveField(
            model_name='report',
            name='gp_reason',
        ),
        migrations.RemoveField(
            model_name='report',
            name='gp_title',
        ),
        migrations.RemoveField(
            model_name='report',
            name='next_move',
        ),
        migrations.RemoveField(
            model_name='report',
            name='outline2',
        ),
        migrations.RemoveField(
            model_name='report',
            name='outline3',
        ),
        migrations.RemoveField(
            model_name='report',
            name='outline4',
        ),
        migrations.RemoveField(
            model_name='report',
            name='problem_outline',
        ),
        migrations.RemoveField(
            model_name='report',
            name='progress2',
        ),
        migrations.RemoveField(
            model_name='report',
            name='progress3',
        ),
    ]
