# Generated by Django 2.2.3 on 2019-07-10 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weekly_report', '0002_auto_20190710_1737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='bp_outline',
            new_name='bad_point',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='deadline1',
            new_name='deadline',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='gp_outline',
            new_name='good_point',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='outline1',
            new_name='outline',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='progress1',
            new_name='progress',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='total_iwh',
            new_name='total_internal_working_hours',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='total_poh',
            new_name='total_project_overtime_hours',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='total_pwh',
            new_name='total_project_working_hours',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='weekly_iwh',
            new_name='weekly_internal_working_hours',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='weekly_poh',
            new_name='weekly_project_overtime_hours',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='weekly_pwh',
            new_name='weekly_project_working_hours',
        ),
        migrations.AddField(
            model_name='report',
            name='problem_outline',
            field=models.TextField(blank=True),
        ),
    ]
