# Generated by Django 2.2.3 on 2019-07-11 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('weekly_report', '0003_auto_20190710_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='report',
            name='progress',
        ),
        migrations.AddField(
            model_name='report',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
